#ifndef HEADER
#define HEADER
#include <QtWidgets\qlineedit.h>
#include <QtWidgets\qapplication.h>
#include <QtWidgets\qpushbutton.h>
#include <qtwidgets\qlayout.h>
#include <QtWidgets\qcombobox.h>
#include <QtWidgets\qtextbrowser.h>
#include <QtWidgets\qlabel.h>
#include <QtWidgets\qmessagebox.h>
#include <QtCore\qmap.h>
#include <QtCore\qbytearray.h>
#include <QtCore\qdatastream.h>
#include <QtCore\qtextstream.h>
#include <QtCore\qfile.h>
#include <QtNetwork\qhostaddress.h>
#include <QtNetwork\qtcpserver.h>
#include <QtNetwork\qtcpsocket.h>
#endif HEADER